GET http://localhost:4000/cat HTTP/1.1

###

GET http://localhost:4000/cat/1 HTTP/1.1

###

POST http://localhost:4000/cat HTTP/1.1
content-type: application/json

{
    "name": "Moka",
    "color": "black",
    "is_cute": false
}

###

DELETE http://localhost:4000/cat/1 HTTP/1.1